---
remote_theme: just-the-docs/just-the-docs
---

title: Paris Postdocs Seminars
author: Savandara Besse (in collaboration with Paris postdocs Consortium)
description: PPS Official Website


# Optional: Navigation order (used by Just the Docs)
nav_sort: case_insensitive

# Plugins GitHub Pages supports
plugins:
  - jekyll-remote-theme

footer_content: |
  <a href="https://bsky.app/profile/parispostdocs.bsky.social" target="_blank">
    <img src="/assets/bluesky-icon.png" alt="Bluesky" style="height: 30px; margin: 0 10px;">
  </a>
  <a href="https://www.linkedin.com/company/paris-postdocs-seminars" target="_blank">
    <img src="/assets/linkedin-icon.png" alt="LinkedIn" style="height: 30px; margin: 0 10px;">
  </a>
  <br>
  📧 <a href="mailto:paris.postdocs@gmail.com">paris.postdocs@gmail.com</a>


# Disable strict front matter
strict_front_matter: false